[build]
  base    = "projects/projekt-ai-website/src/projekt-ai-website"
  publish = "dist"
  command = "npm install && npm run clean:dist && npm run build:prod"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
