services:
  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: projekt-ai-website:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    # No environment variables required for static site
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
  # No environment variables required for static site
