version: '3'

services:
  app:
    volumes:
      # Mount local code for development
      - ./views:/app/views
      - ./routes:/app/routes
      - ./app.js:/app/app.js
      - ./public:/app/public
    environment:
      - NODE_ENV=development 